version: '3.8'

services:

  db:
    platform: linux/x86_64
    image: mysql:8.0-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      #Sample DB to play around!
      - ./prisma/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      #The actual volume is commented, so you don't have to worry to delete it after the test!
      #- db_data:/var/lib/mysql

    #This is necessary because, since I want to provide you with a pre-populated database to work with, it's important to wait for the import of the initdb.sql to complete. 
    #Periodic checks are performed to ensure everything is okay. Once it passes the healthy check, the "backend" service is also launched.
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 20s
      interval: 10s
      timeout: 20s
      retries: 55
    
  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
    - "80:3000"   
  
#volumes:
#  db_data: