version: '3.8'

services:

  db:
    platform: linux/x86_64
    image: mysql:8.0-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      #Sample DB to play around!
      - ./prisma/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      #The actual volume is commented, so you don't have to worry to delete it after the test!
      #- db_data:/var/lib/mysql
    
  backend:
    build: .
    depends_on:
      - db
    ports:
    - "80:3000"   
  
#volumes:
#  db_data: